# Generated by Django 2.2.2 on 2019-12-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='img/standart.png', null=True, upload_to='img', verbose_name='аватарка')),
                ('categoria', models.CharField(choices=[('vd', 'vodka'), ('vn', 'vino'), ('ko', 'koniak'), ('vi', 'viski'), ('ro', 'rom'), ('tk', 'tekila')], max_length=9)),
                ('country', models.CharField(choices=[('arm', 'Армения'), ('pol', 'Польша'), ('rus', 'Россия'), ('ua', 'Украина'), ('bel', 'Беларусь'), ('fin', 'Финляндия'), ('franc', 'Франция'), ('ger', 'Германия'), ('icp', 'Испания')], max_length=9)),
                ('ppm', models.IntegerField(max_length=2)),
                ('volume', models.IntegerField(max_length=3)),
                ('price', models.IntegerField(max_length=5)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'alkogole',
            },
        ),
    ]
