# Generated by Django 2.2.2 on 2019-12-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ppm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
