# Generated by Django 2.2.2 on 2019-12-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_remove_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('vd', 'vodka'), ('vn', 'vino'), ('ko', 'koniak'), ('vi', 'viski'), ('ro', 'rom'), ('tk', 'tekila')], max_length=9, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='country',
            field=models.CharField(choices=[('arm', 'Армения'), ('pol', 'Польша'), ('rus', 'Россия'), ('ua', 'Украина'), ('bel', 'Беларусь'), ('fin', 'Финляндия'), ('franc', 'Франция'), ('ger', 'Германия'), ('icp', 'Испания')], max_length=9, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ppm',
            field=models.IntegerField(verbose_name='градусы'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='item',
            name='volume',
            field=models.FloatField(verbose_name='обьем'),
        ),
    ]
