# Generated by Django 2.2.2 on 2019-12-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20191227_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='имя'),
        ),
    ]
